stacks:
  us-east-1:
    # ACM requires this certificate to be created in us-east-1
    certificate:
      template: certificate.rb
  ap-southeast-2:
    root-domain-bucket:
      template: root_domain_bucket.rb
    subdomain-bucket:
      template: subdomain_bucket.rb
    domain-alias-records:
      template: domain_alias_records.rb
    cloudfront-distribution:
      template: cloudfront_distribution.rb
